### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Nobutaka333** [Nobutaka333/furima-34825#9]
#URL
https://furima-34825.herokuapp.com/
#Basic認証のIDとパスワード
ID:free
Pass:0120
#出品者用のメールアドレスとパスワード
sale@sale.com
sale1234
#購入者用のメールアドレスとパスワード
buy@buy.com
buy1234

**Comment by takumi0530** [comment]
@Nobutaka333 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/113553330-93f88100-9632-11eb-99bf-be76b72b9721.png)
